# Generated by Django 5.1.4 on 2024-12-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_share_app', '0002_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
